Repository couyang24/Firelink, pull requests merged in 2022-04, with the labels that each got.

#3 🤖 Circleci project setup
  .circleci/config.yml
Labels: duplicate, enhancement

#4 :green_heart: fix codeql
  .github/workflows/codeql-analysis.yml
  README.md
Labels: enhancement

#6 :zap: systematically update
  .circleci/config.yml
  .github/workflows/codeql-analysis.yml
  .pre-commit-config.yaml
  README.md
  firelink/__init__.py
  firelink/_version.py
  firelink/fire.py
  firelink/logger.py
  firelink/pipeline.py
  firelink/replace.py
  firelink/tests/__init__.py
  firelink/tests/test_transform.py
  firelink/transform.py
  setup.py
  setup/requirements.txt
Labels: enhancement

#8 :rocket: polished up for pypi
  .circleci/config.yml
  MANIFEST.in
  README.md
  docs/.nojekyll
  docs/Makefile
  docs/conf.py
  docs/developer.rst
  docs/firelink.rst
  docs/firelink.tests.rst
  docs/index.rst
  docs/install.rst
  docs/make.bat
  docs/modules.rst
  docs/setup.rst
  firelink/__init__.py
  firelink/fire.py
  firelink/pipeline.py
  firelink/replace.py
  firelink/tests/test_transform.py
  firelink/transform.py
  playground/README.md
  playground/convert_to_notebook.sh
  playground/demo.py
  requirements.txt
  setup.py
  tests/test_transform.py
Labels: enhancement

#11 :sparkles: Initial commits for spark implementation
  firelink/spark_transform.py
  firelink/transform.py
  setup.py
Labels: enhancement

#12 :sparkles: added spark class and demo
  .gitignore
  README.md
  firelink/spark_transform.py
  playground/demo.py
Labels: enhancement

#13 🚀 Release v0.1.1
  .circleci/config.yml
  .gitignore
  MANIFEST.in
  README.md
  docs/.nojekyll
  docs/Makefile
  docs/conf.py
  docs/developer.rst
  docs/firelink.rst
  docs/firelink.tests.rst
  docs/index.rst
  docs/install.rst
  docs/make.bat
  docs/modules.rst
  docs/setup.rst
  firelink/__init__.py
  firelink/fire.py
  firelink/pipeline.py
  firelink/replace.py
  firelink/spark_transform.py
  firelink/tests/test_transform.py
  firelink/transform.py
  playground/README.md
  playground/convert_to_notebook.sh
  playground/demo.py
  requirements.txt
  setup.py
  tests/test_transform.py
Labels: enhancement

#14 ⬆️ Update version
  firelink/_version.py
  setup.py
Labels: good first issue

#17 :pencil: adding pipeline example
  README.md
Labels: documentation

#18 🐳 update spark/ pandas functions and add doc
  .circleci/config.yml
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_improvement.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/installation_issue.yml
  .github/ISSUE_TEMPLATE/performance_issue.yml
  .github/ISSUE_TEMPLATE/submit_question.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/SECURITY.md
  .github/workflows/publish-package.yml
  .github/workflows/python-package.yml
  README.md
  firelink/_version.py
  firelink/pandas_transform.py
  firelink/spark_transform.py
  playground/README.md
  playground/demo.py
  requirements.txt
  setup.py
  tests/test_transform.py
Labels: bug, documentation, enhancement

#19 :art: docs update
  README.md
  docs/conf.py
  docs/firelink.rst
  docs/firelink.tests.rst
  docs/index.rst
  docs/install.rst
  docs/quickstart.rst
  firelink/__init__.py
  setup.py
Labels: documentation

#20 🐳 update all functions for diagram
  .circleci/config.yml
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_improvement.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/installation_issue.yml
  .github/ISSUE_TEMPLATE/performance_issue.yml
  .github/ISSUE_TEMPLATE/submit_question.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/SECURITY.md
  .github/workflows/publish-package.yml
  .github/workflows/python-package.yml
  README.md
  docs/conf.py
  docs/firelink.rst
  docs/firelink.tests.rst
  docs/index.rst
  docs/install.rst
  docs/quickstart.rst
  firelink/__init__.py
  firelink/_version.py
  firelink/pandas_transform.py
  firelink/spark_transform.py
  playground/README.md
  playground/demo.py
  requirements.txt
  setup.py
  tests/test_transform.py
Labels: enhancement

#23 :white_check_mark: adding pytest
  .circleci/config.yml
  .github/workflows/python-package.yml
  README.md
  docs/conf.py
  docs/refresher.sh
  firelink/pandas_transform.py
  firelink/spark_transform.py
  playground/demo.py
  requirements.txt
  setup.py
  tests/__init__.py
  tests/conftest.py
  tests/test_pandas_transform.py
  tests/test_spark_transform.py
  tests/test_transform.py
Labels: enhancement

#24 :memo: revising git issue
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_improvement.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/installation_issue.yml
  .github/ISSUE_TEMPLATE/performance_issue.yml
  .github/ISSUE_TEMPLATE/submit_question.yml
Labels: documentation

#27 🚀 release for version 0.1.2
  .circleci/config.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_improvement.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/installation_issue.yml
  .github/ISSUE_TEMPLATE/performance_issue.yml
  .github/ISSUE_TEMPLATE/submit_question.yml
  .github/workflows/python-package.yml
  README.md
  docs/conf.py
  docs/refresher.sh
  docs/tests.rst
  firelink/pandas_transform.py
  firelink/spark_transform.py
  playground/demo.py
  requirements.txt
  setup.py
  tests/__init__.py
  tests/conftest.py
  tests/test_pandas_transform.py
  tests/test_spark_transform.py
  tests/test_transform.py
Labels: enhancement
